name: Daily Attendance Task

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 时间 00:00 触发（中国时间 08:00）
  workflow_dispatch: # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install axios dayjs

      - name: Run script
        run: node script.js
