name: Daily Attendance Task

on:
  schedule:
    - cron: "25 22 * * *" # UTC 22:25 (北京时间 6:25)
  workflow_dispatch: # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai # 设置时区为中国时区
      LANG: zh_CN.UTF-8 # 设置语言环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Debug Info
        env:
          TZ: Asia/Shanghai
        run: |
          echo "Current time: $(TZ=Asia/Shanghai date)"
          echo "Timezone: $TZ"
          echo "Language: $LANG"
          echo "Node version: $(node -v)"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Workflow Run ID: ${{ github.run_id }}"

      - name: Install dependencies
        run: |
          npm install axios dayjs moment moment-timezone
          npm list

      - name: Run script
        env:
          TZ: Asia/Shanghai
        run: |
          echo "=== 执行脚本 ==="
          echo "当前时间: $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')"
          node script.js
