name: Daily Task

on:
  schedule:
    - cron: "36 19 * * *"
  workflow_dispatch: # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install axios

      - name: Run script
        run: node script.js
