name: Daily Attendance Task

on:
  schedule:
    - cron: "20,22,24 0 * * *" # UTC 0:20, 0:22, 0:24 (北京时间 8:20, 8:22, 8:24)
  workflow_dispatch: # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai # 设置时区为中国时区
      LANG: zh_CN.UTF-8 # 设置语言环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Debug Info
        run: |
          echo "Current time: $(date)"
          echo "Timezone: $TZ"
          echo "Language: $LANG"
          echo "Node version: $(node -v)"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Workflow Run ID: ${{ github.run_id }}"

      - name: Install dependencies
        run: |
          npm install axios dayjs moment moment-timezone
          npm list

      - name: Run script
        env:
          TZ: Asia/Shanghai
        run: |
          for i in {1..3}; do
            echo "Attempt $i to run script..."
            if node script.js; then
              echo "Script executed successfully"
              break
            else
              echo "Script failed, waiting 30 seconds before retry..."
              sleep 30
            fi
          done
