name: Daily Attendance Task

on:
  schedule:
    - cron: "20 0 * * *" # UTC 00:20（北京时间 08:20）
  workflow_dispatch: # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai # 设置时区为中国时区

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Debug Info
        run: |
          echo "Current time: $(date)"
          echo "Timezone: $TZ"

      - name: Install dependencies
        run: npm install axios dayjs

      - name: Run script
        env:
          TZ: Asia/Shanghai # 确保脚本运行时也使用正确的时区
        run: node script.js
