name: Daily Attendance Task

on:
  schedule:
    - cron: "20 0 * * *" # UTC 0:20 (北京时间 8:20)
  workflow_dispatch: # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai # 设置时区为中国时区
      LANG: zh_CN.UTF-8 # 设置语言环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Debug Info
        run: |
          echo "Current time: $(date)"
          echo "Timezone: $TZ"
          echo "Language: $LANG"
          echo "Node version: $(node -v)"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Workflow Run ID: ${{ github.run_id }}"

      - name: Install dependencies
        run: |
          npm install axios dayjs moment moment-timezone
          npm list

      - name: Run script
        env:
          TZ: Asia/Shanghai
        run: |
          for i in {1..5}; do  # 增加到5次重试
            echo "=== 执行尝试 $i/5 ==="
            echo "当前时间: $(date '+%Y-%m-%d %H:%M:%S')"
            if node script.js; then
              echo "✅ 脚本执行成功"
              exit 0
            else
              echo "❌ 脚本执行失败"
              echo "等待45秒后重试..."
              sleep 45
            fi
          done
          echo "达到最大重试次数，任务失败"
          exit 1
